### ISSUE TITLE
task.py does not handle building relations (multipolygons); tag building relations manually

### ISSUE THREAD

**Issue by bdon** [osmlab/sf_building_height_import#1]

**Comment by maning** [comment]
@bdon How do we do this? I think this is the last blocker to proceed.

**Comment by bdon** [comment]
I will investigate this tomorrow or so - first step is to get a count of total # of building relations that don't have a height tag to see if this is even worth doing

**Comment by bdon** [comment]
There are at most 867 of these:

```
select osm_id from features where osm_id < 0;
```

This is roughly 0.5% of total buildings. I would be more comfortable not making the code more complicated and instead going through and tagging building relations (usually more complex polygons) on a manual basis.

**Comment by maning** [comment]
> There are at most 867 of these:

Yep, same as my count a few weeks back.  

> tagging building relations (usually more complex polygons) on a manual basis. 

Agree, we can create separate task for this or have experienced mappers do this after we finish initial import.

Closing
