### ISSUE TITLE
Buildings with a dimension of < 2 m are ignored

### ISSUE THREAD

**Issue by bdon** [osmlab/sf_building_height_import#11]
We determine heights by shrinking the footprints by 2 meters in order to avoid adjacent buildings. However this excludes 2,088 small buildings that become 1D when shrunk (they then have no intersection with the raster)

```
SELECT osm_id,
       geometry
       from osm_buildings, sf2014_bldg_height
       where st_intersects(rast, ST_Centroid(geometry)) and ST_SummaryStats(ST_Clip(rast,ST_Buffer(geometry,-2),true)) is null;
```

Examples:
http://www.openstreetmap.org/way/261451051
http://www.openstreetmap.org/way/262111842

I think it is an acceptable compromise to not tag these small buildings - many are potentially misidentified parts of larger buildings, and can be reviewed manually later

**Comment by maning** [comment]
👍 , from the sample you provided, they are either backyard sheds or part of a larger building.  Ignoring them in the import make sense.

**Comment by maning** [comment]
Using the new SF building data height, we don't need to do this. Closing.
