### ISSUE TITLE
Orphan nodes

### ISSUE THREAD

**Issue by maning** [osmlab/sf_building_height_import#18]
![screen shot 2016-11-11 at 21 46 03](https://cloud.githubusercontent.com/assets/353700/20221686/5575d698-a858-11e6-88ea-5c2f712db576.png)

Similar to the initial [trial run](https://github.com/osmlab/sf_building_height_import/issues/10#issuecomment-258445208), I'm seeing orphan nodes in the [new test data](http://tasks.openmassing.org/project/11#task/778) these nodes were part of building.  

Let's ignore these nodes in the import if we are not adding any height in the building.  Mappers may delete them during the import and will eventually delete the un-modified building. 

cc/ @chtnha @bdon

**Comment by bdon** [comment]
This seems like a bug with the API for tagging heights. looking into it.

**Comment by bdon** [comment]
@maning this should be fixed by 02b636d now.
