### ISSUE TITLE
Create project in tasks.openstreetmap.us

### ISSUE THREAD

**Issue by maning** [osmlab/sf_building_height_import#20]
Once we are ready to import, create the project in tasks.openstreetmap.us.  

There are UI changes compared to our test instance, specifically the the data download, hyperlink instead of button.

**Comment by bdon** [comment]
OK, I'm creating a new task dataset using an extract https://s3.amazonaws.com/metro-extracts.mapzen.com/san-francisco_california.osm.pbf dated 2016/11/23 (md5 5c4510fef0666bc85383c7529620e38c)

**Comment by bdon** [comment]
exists here: http://tasks.openstreetmap.us/project/70 but not yet published (myself and manings have access)

**Comment by bdon** [comment]
Argh, I just realized that I was using a fork of OSMTM from "osmin" that adds an import_url property to each task. The main OSMTM instance at tasks.openstreetmap.us doesn't have this, so there's no way to generate the correct JOSM URL.

**Comment by bdon** [comment]
https://github.com/hotosm/osm-tasking-manager2/issues/675

**Comment by maning** [comment]
@iandees can you confirm that the import_url feature you and @batpad of tasking manager is deployed in tasks.openstreetmap.us?

**Comment by batpad** [comment]
The feature was merged into TM `master` on May 6th: https://github.com/hotosm/osm-tasking-manager2/pull/767

So if you are using a version that's been updated since then, the feature should exist on `tasks.openstreetmap.us`.

**Comment by bdon** [comment]
It looks like http://tasks.openstreetmap.us/about is on version 2.10
The tag https://github.com/hotosm/osm-tasking-manager2/tree/2.10 is from April 2015, so I suspect the live tasks.osm.us doesn't have this yet.

**Comment by iandees** [comment]
Hey folks, I'm on holiday and have been in transit all day. I can look at upgrading tasks.osm.us when I get to a stopping point here soon.

**Comment by bdon** [comment]
@iandees not urgent. I just tested on labuildingsimport.com TM instance and that has the feature merged in, so we can use that as a backup.

**Comment by iandees** [comment]
Ok, tasks.openstreetmap.us should be upgraded to 2.13.2.

**Comment by maning** [comment]
Thanks @iandees !

**Comment by maning** [comment]
@iandees we tested the http://tasks.openstreetmap.us/project/70 but we got 404 errors. The same project in labuilding works as expected.  I'm not sure what is happening but our hunch is that something went wrong during the migration process to the new version.

```
[Fri Nov 25 2016 10:30:32 GMT+0530 (IST)] body 404 Not Found get /project/70  Error: 404 Not Found get /project/70 
Stack trace:
n.Application.prototype<.error@http://tasks.openstreetmap.us/static/55346924ad17dc9d49251d3b911e9eb9/js/lib/sammy-latest.min.js:8:11873
n.Application.prototype<.notFound@http://tasks.openstreetmap.us/static/55346924ad17dc9d49251d3b911e9eb9/js/lib/sammy-latest.min.js:8:11780
n.Application.prototype<.runRoute@http://tasks.openstreetmap.us/static/55346924ad17dc9d49251d3b911e9eb9/js/lib/sammy-latest.min.js:8:10765
n.Application.prototype<._checkLocation@http://tasks.openstreetmap.us/static/55346924ad17dc9d49251d3b911e9eb9/js/lib/sammy-latest.min.js:8:12185
n.Application.prototype<.run/<@http://tasks.openstreetmap.us/static/55346924ad17dc9d49251d3b911e9eb9/js/lib/sammy-latest.min.js:8:8460
n.Application.prototype<.bind/i@http://tasks.openstreetmap.us/static/55346924ad17dc9d49251d3b911e9eb9/js/lib/sammy-latest.min.js:8:7304
n.event.dispatch@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:3:12392
n.event.add/r.handle@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:3:9156
n.event.trigger@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:3:11571
.trigger/<@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:3:18983
.each@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:2:2879
n.prototype.each@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:2:844
.trigger@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:3:18962
n.Application.prototype<.trigger@http://tasks.openstreetmap.us/static/55346924ad17dc9d49251d3b911e9eb9/js/lib/sammy-latest.min.js:8:7468
.bind/<@http://tasks.openstreetmap.us/static/55346924ad17dc9d49251d3b911e9eb9/js/lib/sammy-latest.min.js:8:3089
n.event.dispatch@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:3:12392
n.event.add/r.handle@http://tasks.openstreetmap.us/static/c07f2267a050732b752cc3e7a06850ac/js/lib/jquery-1.12.3.min.js:3:9156
clearSelection@http://tasks.openstreetmap.us/static/14c68ac097fa8e595370b2eac84eff62/js/project.js:186:5
createMap/<@http://tasks.openstreetmap.us/static/14c68ac097fa8e595370b2eac84eff62/js/project.js:146:9
o.Mixin.Events.fireEvent@http://tasks.openstreetmap.us/static/57ff70669f76ceeaa710f1064387fa14/js/lib/leaflet.js:6:4940
o.Map<._fireMouseEvent@http://tasks.openstreetmap.us/static/57ff70669f76ceeaa710f1064387fa14/js/lib/leaflet.js:6:29476
o.Map<._onMouseClick@http://tasks.openstreetmap.us/static/57ff70669f76ceeaa710f1064387fa14/js/lib/leaflet.js:6:29121
o.DomEvent.addListener/s@http://tasks.openstreetmap.us/static/57ff70669f76ceeaa710f1064387fa14/js/lib/leaflet.js:8:20302
```

**Comment by iandees** [comment]
Where are you getting 404 errors?

**Comment by iandees** [comment]
I should be more precise: I see that 404 error in the console too, but everything on the page seems to work. What's not working for you?

**Comment by maning** [comment]
To reproduce:

* Click `Contribute > Take a task`.
* I get a task assigned to me then error occurred dialog appears

**Comment by iandees** [comment]
The error on the server side that's causing the HTTP 500 response is in the rendering of the response:

```
Traceback (most recent call last):
  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)                                                                                   File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/osmtm/templates/task.mako", line 60, in render_body
    <%include file="task.instructions.mako" />
  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 761, in _include_file
    callable_(ctx, **kwargs)
  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/osmtm/templates/task.instructions.mako", line 4, in render_body
    <%
  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/osmtm/models.py", line 394, in get_extra_instructions          return instructions.format(**properties)
KeyError: u'import_url'
```

Does your GeoJSON specify the property `import_url`?

**Comment by bdon** [comment]
Yes, each feature in the GeoJSON has the key import_url in the "properties" attribute.

**Comment by iandees** [comment]
Did you create this project before I did the upgrade? I bet the data in the database doesn't contain the `import_url` that it expects and the migration process doesn't include the extra properties either. 

Try re-creating the project?

**Comment by bdon** [comment]
@iandees thanks, it works now. http://tasks.openstreetmap.us/project/71

**Comment by batpad** [comment]
@iandees :-( - sorry, the back-end should not have barfed and returned a 500 like that if a key was missing. I've filed an issue for this: https://github.com/hotosm/osm-tasking-manager2/issues/900 - thanks so much for taking care of this, and for identifying the issue.

**Comment by maning** [comment]
Great! Thanks @iandees for debugging the issues and @batpad for filing the ticket. No next actions. Closing

**Comment by bdon** [comment]
@iandees http://tasks.openstreetmap.us is returning 502 errors - possibly down?

**Comment by iandees** [comment]
Yep, working on it. I upgraded the server it's running on and that seems to have caused python problems.

**Comment by iandees** [comment]
Should be back. Sorry about that!

**Comment by bdon** [comment]
Thanks!
