### ISSUE TITLE
Announce import plan to community for review 

### ISSUE THREAD

**Issue by bdon** [osmlab/sf_building_height_import#4]
mailing list to hit:
- [x] talk-us
- [x] SF bay area mappers
- [x] imports-us
- [x] imports

**Comment by maning** [comment]
@bdon @chtnha

Draft email for discussion here: https://gist.github.com/maning/260559d3f1532ff03f061a7d76185c32

Once I get your 👍 , I'll post to the above lists.

**Comment by talllguy** [comment]
@maning I forked and edited the post for ya. Readability is now grade 5 level, which should be good for the list. :) Feel free to use / edit / comment

https://gist.github.com/talllguy/914b20373d4043fec799dee7b58bb68d

**Comment by bdon** [comment]
We should also periodically send progress updates to the mailing list
