### ISSUE TITLE
Better style for LIDAR TMS?

### ISSUE THREAD

**Issue by maning** [osmlab/sf_building_height_import#5]
![lidar_style](https://cloud.githubusercontent.com/assets/353700/18156324/0a734e6c-7033-11e6-911e-6c428a9248f7.gif)

I made this quick viz in QGIS combining hillshade and colored heights.  Could we do the same for the TMS we load in JOSM/iD?  This gives better context for mappers during the import process.

**Comment by bdon** [comment]
Sure. Can you put the qgis project file in the github repo? Or provide a mapnik XML? if it's just the QGIS file you can put that in and I'll try to make a corresponding mapnik xml to serve it up

**Comment by maning** [comment]
@bdon, here's the project file I created in QGIS: https://github.com/osmlab/sf_building_height_import/commit/5ea78bf1f4a03104b133aaa2962e35a8a408d901

The rendering is a combination of two rasters:
1. Building height from SF - colored by height
2. Hillshade - processed from original building height raster.

I have the rasters in Dropbox, happy to share if you don't want to process them.  But hillshade is fairly straightforward in QGIS: in the File menu, click `Raster > Analysis > DEM (Terrain Models)`

**Comment by bdon** [comment]
![screen shot 2016-09-03 at 10 06 37 pm](https://cloud.githubusercontent.com/assets/77501/18228580/0ec1dd66-7223-11e6-9498-6a2a9540f3a0.png)

OK, pre-rendered a TMS layer for zooms 10-19 - uploading to s3 now

**Comment by bdon** [comment]
Tile layer is live at tms:https://s3-us-west-2.amazonaws.com/openmassing/sf_lidar/{z}/{x}/{y}.png - can add to JOSM. please verify this works for you @maning

**Comment by bdon** [comment]
zooms 10-19 and overzooming also seems to work fine

**Comment by maning** [comment]
@bdon TMS works!
