### ISSUE TITLE
Use tasks.openstreetmap.us?

### ISSUE THREAD

**Issue by maning** [osmlab/sf_building_height_import#6]
Any specific reason of not using http://tasks.openstreetmap.us/?
IMO, we can get more people involved if we use that instance.

**Comment by bdon** [comment]
Sure, we can use that when the project is live - but I don't have admin rights there, so for testing let's stay with the current instance - useful because once project is created I can't edit the task geometries

**Comment by maning** [comment]
@bdon, will ask admin to give you project creation permission.  Yes, lets use your instance for testing and trials.

**Comment by maning** [comment]
@iandees, can we add @bdon as "project manager"?  He will lead in the creations of project for the import.  Advance thanks!

**Comment by iandees** [comment]
Yep! @bdon is set up.

**Comment by maning** [comment]
Thanks @iandees !
